### PR TITLE
Give better error message when calling Parallel() without replicate()

### PR DESCRIPTION
**Pull request by carlini**
Currently if you forget to call `replicate()` on a `Parallel` module, it dies somewhere in JaX land in between the 5th and 6th circles of hell. This error makes it possible to understand what's going on and find your way back.

### CODE REVIEW

**Comment by carlini** [comment]
I see, I didn't quite understand how JaX tracing works. It looks like when you call `Jit()` on a `Parallel` module, it passes a `Tracer` which obviously isn't a Sharded array. One potential fix is to special-case allow the `Jit` to do this. @david-berthelot, do you have thoughts?

**Review by david-berthelot — COMMENTED** [review]
> I see, I didn't quite understand how JaX tracing works. It looks like when you call `Jit()` on a `Parallel` module, it passes a `Tracer` which obviously isn't a Sharded array. One potential fix is to special-case allow the `Jit` to do this. @david-berthelot, do you have thoughts?

1. Generally speaking don't put a Parallel call inside Jit. (Parallel is a bit like a Jit already)
2. For your question I would simply do something like `isinstance(v, [ShardedDeviceArray, Tracer...])` (not sure what exactly the `Tracer...` class full name is.

**Comment by carlini** [comment]
The reason I found this bug is one of the tests calls Jit on Parallel. Maybe we should fix that too then.

**Comment by david-berthelot** [comment]
> The reason I found this bug is one of the tests calls Jit on Parallel. Maybe we should fix that too then.

Yes, it's just I don't know how to fix it, apart from checking the module passed to Parallel is `isinstance(module, objax.Jit)` but that doesn't appear robust (since one could pass a function instead). That being said, even if it's not perfect, if it catches 90% of user errors that would be great anyway.

**Review by david-berthelot — DISMISSED** [review]

**Comment by carlini** [comment]
I can't reproduce this test case failing. When I run it on my machine it passes. @david-berthelot could you try running this on your machine and see if it works too?

**Comment by david-berthelot** [comment]
It seems reproducible on my machine
```python
import jax, jaxlib
jax.__version__
# '0.2.1'
jaxlib.__version__
# '0.1.55'
```

That's what I got:
```bash
CUDA_VISIBLE_DEVICES= python3 -m unittest tests/parallel.py

# FAIL: test_jit_parallel_bntrain_concat (tests.parallel.TestParallel)
# FAIL: test_jit_parallel_reducers (tests.parallel.TestParallel)
# Ran 12 tests in 8.739s
# 
# FAILED (failures=2)
```

**Comment by carlini** [comment]
JaX version did it. It works on 0.1.63

**Comment by carlini** [comment]
Jax added a new type of tracer; pushed a simple fix.

**Review by david-berthelot — APPROVED** [review]

**Pull request merged**
